# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["charles.eckman@fastly.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-empty"
description = "At the margins of RFC 9110."
language = "rust"
manifest_version = 3
name = "kitty-header"
service_id = "NRF5TZWykaNWzn1WCb7hj2"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
